project_root: /home/aaron/workspace/carla/leaderboard-devkit
save_root: /data/leaderboard/results/lbc/privileged/debug/template
save_images: False
split: devtest
weights_path: team_code/lbc/config/expectation_retrained.ckpt
temperature: 0.0000001 # 1e-7
