project_root: /home/aaron/workspace/carla/leaderboard-devkit
save_root: /data/leaderboard/results/lbc/xodrmap/debug/template
save_images: False
split: devtest
weights_path: team_code/lbc/config/weights/image_model.ckpt
