wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.29
    code_path: code/team_code/rl/dspred/map_model.py
    framework: torch
    is_jupyter_run: false
    python_version: 3.7.9
batch_size:
  desc: null
  value: 32
command_coefficient:
  desc: null
  value: 0.1
dataset_dir:
  desc: null
  value: /data/leaderboard/data/lbc/CARLA_challenge_autopilot
hack:
  desc: null
  value: false
heatmap_radius:
  desc: null
  value: 5
id:
  desc: null
  value: 7bf7d72a780246988df2be5494ca2457
lr:
  desc: null
  value: 0.0001
max_epochs:
  desc: null
  value: 50
sample_by:
  desc: null
  value: even
save_dir:
  desc: null
  value: checkpoints/7bf7d72a780246988df2be5494ca2457
temperature:
  desc: null
  value: 10.0
weight_decay:
  desc: null
  value: 0.0
