project_root: /home/aaron/workspace/carla/leaderboard-devkit
save_root: /data/leaderboard/results/rl/dspred/debug/template
save_data: False
save_debug: False
env:
    placeholder: 0
agent:
    #weights_path: /data/aaronhua/leaderboard/training/dqn/offline/20210422_194030/epoch=24.ckpt
    #weights_path: /data/aaronhua/leaderboard/training/dqn/offline/20210423_175643/epoch=11.ckpt
  weights_path: /ssd1/aaronhua/leaderboard/training/dqn/offline/debug/20210427_141614/epoch=16.ckpt
  expert_path: /data/aaronhua/leaderboard/training/lbc/map_model/20210405_225046/epoch=22.ckpt
  waypoint_mode: argmax # or argmax
  dagger_expert: false
  data_hack: false
  forward: false
  n: 20
  mode: none

