project_root: /home/aaron/workspace/carla/leaderboard-devkit
save_root: /data/leaderboard/results/rl/dspred/debug/template
save_data: False
save_debug: False
env:
    world_port: 2000
agent:
  weights_path: /data/aaronhua/leaderboard/training/dqn/offline/20210505_012216/last.ckpt
  expert_path: /data/aaronhua/leaderboard/training/lbc/map_model/20210405_225046/epoch=22.ckpt
  waypoint_mode: argmax # or argmax
  dagger_expert: false
  data_hack: false
  forward: false
  n: 20
  #control_mode: points # or learned

