project_root: /home/aaron/workspace/carla/leaderboard-devkit
save_root: /data/leaderboard/results/rl/dspred/debug/template
save_data: False
save_debug: False
env:
  world_port: 2000
  trafficmanager_port: 8000
  trafficmanager_seed: 0
  routes: routes_training.xml
  scenarios: no_traffic_scenarios.json
  repetitions: 1
  empty: false
  random: false
  short_stop: false
agent:
    #weights_path: /data/aaronhua/leaderboard/training/lbc/map_model/20210403_235158/epoch=44.ckpt
  #weights_path: /data/aaronhua/leaderboard/training/dqn/offline/20210419_212350/epoch=9.ckpt
  expert_path: /data/aaronhua/leaderboard/training/lbc/map_model/20210405_225046/epoch=22.ckpt
  waypoint_mode: softargmax # or argmax
  safety_driver: false
  total_timesteps: 500000
  burn_timesteps: 2000
  buffer_size: 50000
  batch_size: 32
  n: 20
  epsilon: 0.1
  forward: false

